# Production Profile Configuration
spring:
  # Database Configuration for Production
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pockito}
    username: ${DATABASE_USERNAME:pockito}
    password: ${DATABASE_PASSWORD:pockito}
  
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway Configuration for Production
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging Configuration for Production
logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
    com.pockito: INFO
    org.springdoc: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Production-specific settings
server:
  port: ${SERVER_PORT:8080}

# CORS Configuration for production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourdomain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type

# Actuator Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
