# Development Profile Configuration
spring:
  # Database Configuration for Development
  datasource:
    url: jdbc:postgresql://localhost:5434/pockito
    username: pockito
    password: pockito
  
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Flyway Configuration for Development
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging Configuration for Development
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    com.pockito: DEBUG
    org.springdoc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development-specific settings
server:
  port: 8080

# CORS Configuration for local development
cors:
  allowed-origins: http://localhost:4200, http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
