-- Migration: Create Wallet table
-- Version: V5
-- Description: Creates the t_wallet table for storing user wallets with proper constraints and indexes

CREATE TABLE t_wallet (
    id UUID NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    initial_balance DECIMAL(17,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    icon_url VARCHAR(500),
    goal_amount DECIMAL(17,2),
    type VARCHAR(20) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    order_position INTEGER NOT NULL,
    description VARCHAR(500),
    color VARCHAR(7),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    archived_at TIMESTAMP,
    archived_by VARCHAR(255),
    version BIGINT,
    
    -- Primary key constraint
    CONSTRAINT pk_wallet PRIMARY KEY (id),
    
    -- Foreign key constraint to user table
    CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES app_user(username),
    
    -- Unique constraint: no duplicate wallet names per user
    CONSTRAINT uk_wallet_user_name UNIQUE (user_id, name),
    
    -- Check constraints for data validation
    CONSTRAINT chk_wallet_name_length CHECK (LENGTH(name) >= 1 AND LENGTH(name) <= 100),
    CONSTRAINT chk_wallet_goal_amount_positive CHECK (goal_amount IS NULL OR goal_amount >= 0),
    CONSTRAINT chk_wallet_order_position_non_negative CHECK (order_position >= 0),
    CONSTRAINT chk_wallet_color_format CHECK (color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_wallet_type_valid CHECK (type IN ('BANK_ACCOUNT', 'CASH', 'CREDIT_CARD', 'SAVINGS', 'CUSTOM'))
);

-- Create indexes for performance optimization
CREATE INDEX idx_wallet_user_id ON t_wallet(user_id);
CREATE INDEX idx_wallet_is_default ON t_wallet(is_default);
CREATE INDEX idx_wallet_type ON t_wallet(type);
CREATE INDEX idx_wallet_order_position ON t_wallet(order_position);

-- Create composite index for user_id + order_position for efficient ordering
CREATE INDEX idx_wallet_user_order ON t_wallet(user_id, order_position);

-- Create index for currency filtering
CREATE INDEX idx_wallet_currency ON t_wallet(currency);

-- Add comments for documentation
COMMENT ON TABLE t_wallet IS 'Stores user wallets with their financial information and customization options';
COMMENT ON COLUMN t_wallet.id IS 'Primary key - UUID generated by Hibernate uuid2 generator';
COMMENT ON COLUMN t_wallet.user_id IS 'Foreign key reference to the user who owns this wallet';
COMMENT ON COLUMN t_wallet.name IS 'Wallet name - must be unique per user (1-100 characters)';
COMMENT ON COLUMN t_wallet.initial_balance IS 'Initial balance of the wallet (precision: 17,2)';
COMMENT ON COLUMN t_wallet.currency IS 'Currency code following ISO 4217 standard (3-letter code)';
COMMENT ON COLUMN t_wallet.icon_url IS 'URL to the wallet icon/image (optional, max 500 characters)';
COMMENT ON COLUMN t_wallet.goal_amount IS 'Goal amount for the wallet, e.g., savings target (optional, precision: 17,2)';
COMMENT ON COLUMN t_wallet.type IS 'Wallet type/category (BANK_ACCOUNT, CASH, CREDIT_CARD, SAVINGS, CUSTOM)';
COMMENT ON COLUMN t_wallet.is_default IS 'Whether this wallet is the user default wallet';
COMMENT ON COLUMN t_wallet.order_position IS 'Display order position for the wallet (non-negative integer)';
COMMENT ON COLUMN t_wallet.description IS 'Description of the wallet (optional, max 500 characters)';
COMMENT ON COLUMN t_wallet.color IS 'Hex color code for the wallet (optional, format: #A1B2C3)';
COMMENT ON COLUMN t_wallet.created_at IS 'Timestamp when the wallet was first created';
COMMENT ON COLUMN t_wallet.updated_at IS 'Timestamp when the wallet was last updated';
COMMENT ON COLUMN t_wallet.created_by IS 'Username of who created the wallet record';
COMMENT ON COLUMN t_wallet.updated_by IS 'Username of who last updated the wallet record';
COMMENT ON COLUMN t_wallet.archived_at IS 'Timestamp when the wallet was archived (soft delete)';
COMMENT ON COLUMN t_wallet.archived_by IS 'Username of who archived the wallet record';
COMMENT ON COLUMN t_wallet.version IS 'Hibernate optimistic locking version';