-- Migration: Create Category table
-- Version: V3
-- Description: Creates the t_category table for storing user-defined categories with hierarchical support

CREATE TABLE t_category (
    id UUID NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) NOT NULL,
    category_type VARCHAR(10) NOT NULL,
    icon_url VARCHAR(500),
    parent_category_id UUID,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    archived_at TIMESTAMP,
    archived_by VARCHAR(255),
    version BIGINT,
    
    -- Primary key constraint
    CONSTRAINT pk_category PRIMARY KEY (id),
    
    -- Foreign key constraint to user table
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES app_user(username),
    
    -- Foreign key constraint to parent category (self-reference)
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id) REFERENCES t_category(id),
    
    -- Unique constraint: no duplicate category names per user
    CONSTRAINT uk_category_user_name UNIQUE (user_id, name),
    
    -- Check constraints for data validation
    CONSTRAINT chk_category_name_length CHECK (LENGTH(name) >= 1 AND LENGTH(name) <= 100),
    CONSTRAINT chk_category_color_format CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT chk_category_type_valid CHECK (category_type IN ('EXPENSE', 'INCOME')),
    CONSTRAINT chk_category_icon_url_length CHECK (icon_url IS NULL OR LENGTH(icon_url) <= 500),
    CONSTRAINT chk_category_no_self_parent CHECK (parent_category_id IS NULL OR parent_category_id != id)
);

-- Create indexes for performance optimization
CREATE INDEX idx_category_user_id ON t_category(user_id);
CREATE INDEX idx_category_parent_id ON t_category(parent_category_id);
CREATE INDEX idx_category_type ON t_category(category_type);

-- Create composite index for user_id + name for efficient unique constraint checking
CREATE INDEX idx_category_user_name ON t_category(user_id, name);

-- Create composite index for user_id + category_type for efficient filtering
CREATE INDEX idx_category_user_type ON t_category(user_id, category_type);

-- Create index for color filtering
CREATE INDEX idx_category_color ON t_category(color);

-- Create index for hierarchical queries (parent-child relationships)
CREATE INDEX idx_category_hierarchy ON t_category(parent_category_id, user_id);

-- Add comments for documentation
COMMENT ON TABLE t_category IS 'Stores user-defined categories for organizing transactions or other entities with hierarchical support';
COMMENT ON COLUMN t_category.id IS 'Primary key - UUID generated by Hibernate uuid2 generator';
COMMENT ON COLUMN t_category.user_id IS 'Foreign key reference to the user who owns this category';
COMMENT ON COLUMN t_category.name IS 'Category name - must be unique per user (1-100 characters)';
COMMENT ON COLUMN t_category.color IS 'Hex color code for the category (required, format: #A1B2C3)';
COMMENT ON COLUMN t_category.category_type IS 'Type of category - either EXPENSE or INCOME (required)';
COMMENT ON COLUMN t_category.icon_url IS 'URL to the category icon/image (optional, max 500 characters)';
COMMENT ON COLUMN t_category.parent_category_id IS 'Foreign key reference to parent category for hierarchical organization (optional)';
COMMENT ON COLUMN t_category.created_at IS 'Timestamp when the category was first created';
COMMENT ON COLUMN t_category.updated_at IS 'Timestamp when the category was last updated';
COMMENT ON COLUMN t_category.created_by IS 'Username of who created the category record';
COMMENT ON COLUMN t_category.updated_by IS 'Username of who last updated the category record';
COMMENT ON COLUMN t_category.archived_at IS 'Timestamp when the category was archived (soft delete)';
COMMENT ON COLUMN t_category.archived_by IS 'Username of who archived the category record';
COMMENT ON COLUMN t_category.version IS 'Hibernate optimistic locking version';
