-- Migration: Create Transaction table
-- Version: V6
-- Description: Creates the t_transaction table for storing financial transactions between wallets

CREATE TABLE t_transaction (
    id UUID NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    wallet_from_id UUID,
    wallet_to_id UUID,
    amount DECIMAL(17,2) NOT NULL,
    exchange_rate DECIMAL(17,6) NOT NULL DEFAULT 1.000000,
    note VARCHAR(1000),
    effective_date DATE NOT NULL,
    category_id UUID,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    archived_at TIMESTAMP,
    archived_by VARCHAR(255),
    version BIGINT,
    
    -- Primary key constraint
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    
    -- Foreign key constraint to user table
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES app_user(username),
    
    -- Foreign key constraint to source wallet
    CONSTRAINT fk_transaction_wallet_from FOREIGN KEY (wallet_from_id) REFERENCES t_wallet(id),
    
    -- Foreign key constraint to destination wallet
    CONSTRAINT fk_transaction_wallet_to FOREIGN KEY (wallet_to_id) REFERENCES t_wallet(id),
    
    -- Foreign key constraint to category
    CONSTRAINT fk_transaction_category FOREIGN KEY (category_id) REFERENCES t_category(id),
    
    -- Check constraints for data validation
    CONSTRAINT chk_transaction_type_valid CHECK (transaction_type IN ('TRANSFER', 'EXPENSE', 'INCOME')),
    CONSTRAINT chk_transaction_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_transaction_exchange_rate_positive CHECK (exchange_rate > 0),
    CONSTRAINT chk_transaction_note_length CHECK (note IS NULL OR LENGTH(note) <= 1000),
    CONSTRAINT chk_transaction_wallet_from_to_different CHECK (wallet_from_id IS NULL OR wallet_to_id IS NULL OR wallet_from_id != wallet_to_id),
    
    -- Business logic constraints
    -- TRANSFER: requires both wallets (one can be NULL for external transfers)
    -- EXPENSE: requires wallet_from, category recommended
    -- INCOME: requires wallet_to, category recommended
    CONSTRAINT chk_transaction_transfer_wallets CHECK (
        transaction_type != 'TRANSFER' OR 
        (wallet_from_id IS NOT NULL OR wallet_to_id IS NOT NULL)
    ),
    CONSTRAINT chk_transaction_expense_wallet_from CHECK (
        transaction_type != 'EXPENSE' OR wallet_from_id IS NOT NULL
    ),
    CONSTRAINT chk_transaction_income_wallet_to CHECK (
        transaction_type != 'INCOME' OR wallet_to_id IS NOT NULL
    )
);

-- Create indexes for performance optimization
CREATE INDEX idx_transaction_user_id ON t_transaction(user_id);
CREATE INDEX idx_transaction_type ON t_transaction(transaction_type);
CREATE INDEX idx_transaction_effective_date ON t_transaction(effective_date);
CREATE INDEX idx_transaction_wallet_from ON t_transaction(wallet_from_id);
CREATE INDEX idx_transaction_wallet_to ON t_transaction(wallet_to_id);
CREATE INDEX idx_transaction_category ON t_transaction(category_id);

-- Create composite indexes for common query patterns
CREATE INDEX idx_transaction_user_type ON t_transaction(user_id, transaction_type);
CREATE INDEX idx_transaction_user_date ON t_transaction(user_id, effective_date);
CREATE INDEX idx_transaction_user_wallet_from ON t_transaction(user_id, wallet_from_id);
CREATE INDEX idx_transaction_user_wallet_to ON t_transaction(user_id, wallet_to_id);
CREATE INDEX idx_transaction_user_category ON t_transaction(user_id, category_id);

-- Create index for date range queries
CREATE INDEX idx_transaction_effective_date_desc ON t_transaction(effective_date DESC);

-- Create index for wallet transaction history
CREATE INDEX idx_transaction_wallet_from_date ON t_transaction(wallet_from_id, effective_date);
CREATE INDEX idx_transaction_wallet_to_date ON t_transaction(wallet_to_id, effective_date);

-- Add comments for documentation
COMMENT ON TABLE t_transaction IS 'Stores financial transactions between wallets with support for transfers, expenses, and income';
COMMENT ON COLUMN t_transaction.id IS 'Primary key - UUID generated by Hibernate uuid2 generator';
COMMENT ON COLUMN t_transaction.user_id IS 'Foreign key reference to the user who owns this transaction';
COMMENT ON COLUMN t_transaction.transaction_type IS 'Type of transaction - TRANSFER, EXPENSE, or INCOME';
COMMENT ON COLUMN t_transaction.wallet_from_id IS 'Foreign key reference to source wallet (required for TRANSFER and EXPENSE)';
COMMENT ON COLUMN t_transaction.wallet_to_id IS 'Foreign key reference to destination wallet (required for TRANSFER and INCOME)';
COMMENT ON COLUMN t_transaction.amount IS 'Base transaction amount in source wallet currency (precision: 17,2)';
COMMENT ON COLUMN t_transaction.exchange_rate IS 'Exchange rate for currency conversion (precision: 17,6, default: 1.000000)';
COMMENT ON COLUMN t_transaction.note IS 'Optional note providing additional transaction details (max 1000 characters)';
COMMENT ON COLUMN t_transaction.effective_date IS 'Date when the transaction takes effect';
COMMENT ON COLUMN t_transaction.category_id IS 'Foreign key reference to category (applicable for EXPENSE and INCOME)';
COMMENT ON COLUMN t_transaction.created_at IS 'Timestamp when the transaction was first created';
COMMENT ON COLUMN t_transaction.updated_at IS 'Timestamp when the transaction was last updated';
COMMENT ON COLUMN t_transaction.created_by IS 'Username of who created the transaction record';
COMMENT ON COLUMN t_transaction.updated_by IS 'Username of who last updated the transaction record';
COMMENT ON COLUMN t_transaction.archived_at IS 'Timestamp when the transaction was archived (soft delete)';
COMMENT ON COLUMN t_transaction.archived_by IS 'Username of who archived the transaction record';
COMMENT ON COLUMN t_transaction.version IS 'Hibernate optimistic locking version';
